# Generated by Django 2.1.5 on 2019-01-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=120, null=True)),
                ('productManufacturingCity', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=120, null=True)),
                ('transaction_Amount', models.CharField(blank=True, max_length=120, null=True)),
                ('transaction_DateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
